# Kafka Configuration
kafka.bootstrap.servers=kafka:9092
kafka.payment.topic=payment-events
kafka.user.registration.topic=notifications.registration.events
kafka.user.reset.topic=notifications.reset.password.events

# MongoDB Configuration
mongodb.connection.string=mongodb://mongodb:27017/notificationdb
mongodb.database=notificationdb

# Email Configuration
email.smtp.host=smtp.yandex.ru
email.smtp.port=587
email.smtp.username=<login>@yandex.ru
email.smtp.password=<pass>
email.smtp.auth=true
email.smtp.starttls.enable=true
email.from=<login>@yandex.ru

# Application Settings
notification.retry.attempts=3
notification.retry.delay=5000

