spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.bankx.notification.dto.kafka

kafka:
  topics:
    user-registered: "users.stream"
    payment-processed: "payments.stream"