# Kafka (?????? consumer)
kafka.bootstrap.servers=kafka:9092
kafka.consumer.enable.auto.commit=true
kafka.consumer.auto.offset.reset=earliest
kafka.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.max.poll.records=50

# Kafka Topic Names
kafka.payment.topic=notifications.transaction.events
kafka.user.registration.topic=notifications.registration.events
kafka.user.reset.password.topic=notifications.reset.password.events

# Kafka Consumer Groups
kafka.consumer.registration.group=notification-service-registration-group
kafka.consumer.password.reset.group=notification-service-password-reset-group
kafka.consumer.transaction.group=notification-service-transaction-group

# MongoDB Configuration
mongodb.connection.string=mongodb://admin:password@mongodb:27017/bankx-notification?authSource=admin
mongodb.database=bankx-notification

# Email Configuration for Yandex
email.smtp.host=smtp.yandex.ru
email.smtp.port=465
email.smtp.ssl.enable=true
email.smtp.auth=true
email.smtp.username=login@yandex.ru
email.smtp.password=apassword
email.smtp.socketFactory.port=465
email.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
email.from.address=login@yandex.ru

# Application Settings
application.url=http://localhost:8080
activation.link.expiration.hours=24

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.bankx.notification".level=DEBUG